### ISSUE TITLE
[FEATURE]: Global search enhancement

### ISSUE THREAD

**Issue by sagarnaikjuspay** [juspay/hyperswitch-control-center#1625]
- [x] #1627
- [x] #1628
- [x] #1629
- [x] #1630

**Comment by muditbhutani** [comment]
**Expected behaviour:**
1. User will be able to select a category and then provide input against it
2. After entering a space they will be able to select a category again including the category already selected
3. User can provide multiple inputs in fashion of **_"category1:input category2:input category1: input2"_**. Front end will combine the asks and send to api for filtering
4. All categories will be suggestions and not be enforce on the user, they will be able to do blanket search without selecting any category as well
5. For categories where we can handle case insensitivity, we will handle it and where we cannot(customer email, ids etc) user will be informed that this category search will only work with precise case input. For blanket search case insensitivity is already handled, it will stay as is
6. For categories like connector, payment method etc we will dynamically fetch the suggestions based on the data this specific user has access to. Need to evaluate the logic here, if user has access to multiple profiles and merchants we should not power suggestions based on data across multiple profiles and merchants. For v1 we can simplify this logic(to be discussed)
7. Expected categories for phase 1: payment method, payment method type, connector, customer email, card network, last 4

**Comment by muditbhutani** [comment]
>For categories like connector, payment method etc we will dynamically fetch the suggestions based on the data this specific user has access to. Need to evaluate the logic here, if user has access to multiple profiles and merchants we should not power suggestions based on data across multiple profiles and merchants. For v1 we can simplify this logic(to be discussed)

We concluded, we will only fetch the dynamic options from the profile data user is currently part of

**Comment by muditbhutani** [comment]
There is also a scenario where user might have payments but not any data for the specific category, this will result in our suggestions for that specific category being empty

To still allow user with ease of search the design will have suggestions while selecting category

**Comment by muditbhutani** [comment]
Proposed:
Add dates as an extra addition on top of the existing categories. User will be able to filter for connector:stripe but payments of last 7 days and so on

**Comment by muditbhutani** [comment]
Follow up task https://github.com/juspay/hyperswitch-control-center/issues/1878
